name: restoguh_dicoding_fundamentl
description: "Submission 1 dicoding restaurant app yang bernama restoguh restarant owned by teguh"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.2
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.2.1
  flutter_timezone: ^4.1.0
  http: ^1.5.0
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0
  build_runner: ^2.4.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/

  fonts:
    - family: Geometr415
      fonts:
        - asset: assets/fonts/geometri.ttf

    - family: GillSansMT
      fonts:
        - asset: assets/fonts/GillSansMT.ttf

    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/SfUiDisplay-Thin.otf
          weight: 100
        - asset: assets/fonts/SfUiDisplay-Regular.otf
          weight: 400
        - asset: assets/fonts/SfUiDisplay-Bold.otf
          weight: 700   
