name: Flutter CI/CD Fixed

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  check-environment:
    name: Check Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter (Specific Version)
        uses: subosito/flutter-action@v2
        with:
          # ✅ Pilih versi yang kompatibel
          flutter-version: '3.16.9'  # Versi dengan Dart SDK yang sesuai
          
      - name: Debug Info
        run: |
          echo "=== Flutter Version ==="
          flutter --version
          echo "=== Dart Version ==="
          dart --version
          echo "=== Flutter Doctor ==="
          flutter doctor -v

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: check-environment
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'

      - name: Install Dependencies
        run: |
          flutter pub get
          flutter pub deps

      - name: Run Tests
        run: flutter test