name: Flutter CI/CD Fixed

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  check-environment:
    name: Check Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter (Latest Stable with Dart >= 3.9.2)
        uses: subosito/flutter-action@v2
        with:
          # ✅ FIX: Change to a Flutter version that ships with Dart SDK 3.9.2 or newer.
          # Flutter 3.22.x is the latest stable and uses Dart 3.4.x.
          flutter-version: '3.22.x'
          
      - name: Debug Info
        run: |
          echo "=== Flutter Version ==="
          flutter --version
          echo "=== Dart Version ==="
          dart --version
          echo "=== Flutter Doctor ==="
          flutter doctor -v

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: check-environment
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          # ✅ FIX: Use the same compatible version as above.
          flutter-version: '3.22.x'

      - name: Install Dependencies
        run: |
          # Use --no-prerelease to avoid issues if using a pre-release Flutter channel
          flutter pub get
          flutter pub deps

      - name: Run Tests
        run: flutter test